### ISSUE TITLE
MAX_OPINION_PAGE_COUNT ?

### ISSUE THREAD

**Issue by devlux76** [freelawproject/eyecite#104]
I was doing a code review in preparation for the fix I was asked to work on regarding "scotus" being assigned inappropriately to certain cases.  While reading the code I noticed the following line in resolve.py

```
MAX_OPINION_PAGE_COUNT = 150
```

I was wondering why the 150-page limit when there are cases like _McConnell v. FEC_, 251 F.Supp.2d 176 (D.C. 2003)
that are 750+ pages long. While probably not the majority of cases, some of the more important cases are well in excess of 150 pages and we might be missing out on citations to them by bailing out if the pincite is > page+150 in the _has_invalid_pin_cite function?

**Comment by mlissner** [comment]
This is a judgement call. See discussion here: https://github.com/freelawproject/eyecite/issues/74
