### ISSUE TITLE
Rename NonopinionCitation to UnknownCitation

### ISSUE THREAD

**Issue by mattdahl** [freelawproject/eyecite#109]
`NonopinionCitation` seems like a misnomer now that we have `FullLawCitation` and `FullJournalCitation` abstractions (which are obviously not opinions). The point of `NonopinionCitation` is to serve as a naive catch-all for any citation that can't be otherwise parsed, so I think it should be renamed to something like `UnknownCitation`.

**Comment by mlissner** [comment]
Makes sense. Ah to have a stable API. Someday!

**Comment by mattdahl** [comment]
Uh, so it seems like you agree, but you also closed this issue? Not sure how to interpret :)

**Comment by mlissner** [comment]
Oops, didn't mean to.

**Comment by mattdahl** [comment]
Fixed in #110
