### ISSUE TITLE
diff-match-patch-python can't be built in Python 3.10 on MacOS

### ISSUE THREAD

**Issue by mscarey** [freelawproject/eyecite#114]
I found that eyecite failed to build in Python 3.10 on MacOS during the pip installation of diff-match-patch-python, with the messages "#error Unsupported architecture" and "legacy-install-failure." My problem went away when I replaced that dependency with the current version of [fast-diff-match-patch](https://pypi.org/project/fast-diff-match-patch/), which is the renamed version of [diff-match-patch-python](https://pypi.org/project/diff-match-patch-python/1.0.3/). It wasn't a convenient time for me to install poetry, so I haven't been able to update the lockfile for a proper pull request.

**Comment by mlissner** [comment]
Huh. Curious. We use eyecite in Python 3.10 on Macs, but sounds like we have dependency work to do regardless. I'll get this on...somebody's backlog, I guess.

**Comment by flooie** [comment]
I don't know about macOS which seems to work for me but I have three students that can't install it with Windows.

**Comment by mlissner** [comment]
Just moved this to the top of my backlog. I should be able to get to it today. Have you been working on it?

**Comment by flooie** [comment]
I was going to but I saw it on your list so I demurred.

**Comment by mlissner** [comment]
Should be fixed. Was more work than I'd hoped, but luckily I know the maintainer of the patching library (news to me!) and he was able to push a new version with a fix we needed. Whew!
