### ISSUE TITLE
Best approach to handle Unicode characters in citations

### ISSUE THREAD

**Issue by quevon24** [freelawproject/eyecite#121]
Some citations come with unicode characters and can't be parsed, for example:

- Bayard’s Notebook
- Clayton’s Notebook
- Miller’s Notebook
- Read’s Notebook
- Rodney’s Notes
- Wilson’s Red Book

The examples above contain a left single quotation mark or u"\u2019" [https://ia903104.us.archive.org/7/items/law.free.cap.del-cas.1/338.506697.json](https://ia903104.us.archive.org/7/items/law.free.cap.del-cas.1/338.506697.json)

I've been looking at those unicode characters to see what is the best approach to replace those characters, one way do that is to use chained replace() in the case name string, the problem with this is that we need to identify all the possible Unicode characters and set a replace for them. Beside that this approach is fast.

The other option is to use the unidecode library to replace Unicode characters, this is probably the easiest way to do it, I did some research and shouldn’t affect the performance of using the library, for what I saw in the code, time complexity should be linear. If we don’t expect to have Chinese/Japanese/Korean characters in the case name it shouldn’t be a problem. 

The docs says that mapping between characters is done by choosing characters to be close a human with a US keyboard would choose.
Usually remove accents, diaeresis, etc. and replace symbols to its closest representation.

 For example: 

- ä -> a, á -> a, ç -> c
- Section sign § -> SS

I also checked the okina symbol that @flooie mentioned being in citations, I saw that is used in a lot of Hawaiian words, the okina ʻ is replaced with a grave accent `

For example: 

- 113 Hawaiʻi 60 -> 113 Hawai`i 60

Maybe the only problem with unidecode library is that we are subject to the character suggested by the author of the library.

What do you think is the best approach to handle this? 
Does anyone have any other suggestions?

**Comment by mlissner** [comment]
This sounds like two problems:

1. Left single quotation marks need to get normalized
2. We need to support unicode characters in some citations, like with the okina.

For the left single quotation mark, any chance we make to normalize it would apply to every citation we ingest, so I'd like to see some performance comparisons using the `timeit` module:

 - Replacing the left single quotation mark with a single quotation mark using `replace`
 - Replacing the left single quotation mark with a single quotation mark using a regex
 - Replacing the left single quotation mark with a single quotation mark using unidecode

I'm not excited about unidecode, honestly. It does so much more than the surgical fix we need, introduces a dependency, etc.

For the okina, I think we should decide whether it's correct to have the character as the canonical form or not. If so, then let's support it via the reporters-db as the official form. If not, let's support it via a variation. I haven't researched what's correct, but I suspect that using the okina is correct, and we should make that the canonical form.

**Comment by mlissner** [comment]
(I have an unsubstantiated belief that adding support for a unicode character to the reporters-db and eyecite shouldn't be hard. Both are Python 3, reporters-db is JSON, which supports utf-8. What could go wrong? Have we tried?)

**Comment by quevon24** [comment]
> This sounds like two problems:
> 
> 1. Left single quotation marks need to get normalized
> 2. We need to support unicode characters in some citations, like with the okina.
> 
> For the left single quotation mark, any chance we make to normalize it would apply to every citation we ingest, so I'd like to see some performance comparisons using the `timeit` module:
> 
> * Replacing the left single quotation mark with a single quotation mark using `replace`
> * Replacing the left single quotation mark with a single quotation mark using a regex
> * Replacing the left single quotation mark with a single quotation mark using unidecode
> 
> I'm not excited about unidecode, honestly. It does so much more than the surgical fix we need, introduces a dependency, etc.
> 
> For the okina, I think we should decide whether it's correct to have the character as the canonical form or not. If so, then let's support it via the reporters-db as the official form. If not, let's support it via a variation. I haven't researched what's correct, but I suspect that using the okina is correct, and we should make that the canonical form.

This are the results from timeit module:

Replacing the left single quotation mark with a single quotation mark using replace
`1000000 loops, best of 5: 129 nsec per loop`

Replacing the left single quotation mark with a single quotation mark using a regex
`1000000 loops, best of 5: 613 nsec per loop`

Replacing the left single quotation mark with a single quotation mark using unidecode
`1000000 loops, best of 5: 3.89 usec per loop`

There is a big difference in performance. Definitely if we just want to normalize the left single quotation mark, using replace is the way to go, it's much more faster than any of the others.

**Comment by quevon24** [comment]
I inspected the source code from eyecite to see the best way to implement the normalization of left single quotation mark

I tested three different ways to implement it but i'm not sure which one fits the best or if there is any better option.

The first option is to hardcode the replace method inside the [get_citations()](https://github.com/freelawproject/eyecite/blob/main/eyecite/find.py#L30)

The second option is to use a function including eyecite: [clean_text()](https://github.com/freelawproject/eyecite/blob/main/eyecite/clean.py#L7) which uses different cleaning functions to prepare the citation text and then manually  pass it to get_citations() function, here we need to add a new cleanup function to replace the left single quotation mark, the problem here is that i'm not sure we can consider the replace function as a cleaning function, but we are using it to normalize the text instead of cleaning it, so i'm not 100% it should go there.
If we use this implementation, we will need to add an extra step in harvard importer to prepare the citation before passing it to get_citations() 

The third option is to create a new function to perform the normalization, similar to clean_text() but in this case we will have normalization functions to prepare the citation text, this approach could be useful if we expect to replace more characters in citations in the future, but leaving this as an option for the user in case that wants to use keep the raw text instead of preproccesing it. With this implementation we will also need to add an extra step in harvard importer to prepare the citation before passing it to get_citations()

I already made the three implementations for testing. But which do you think is the best? Or can you think of implementing it in another way?

**Comment by mlissner** [comment]
I don't know offhand, except to say that a new function to do normalization and using clean_text don't feel right. It's probably right to put it in get_citations(), but one other approach is to put it as a regex in reporters_db. So instead of having a quotation mark, you have a regex that matches the left single quotation mark or the regular one. This follows in the established pattern we have for funky things like this, no?

**Comment by quevon24** [comment]
It took me some time to deeply inspect "eyecite" to see how are handled the reporters’ names.

I came to these possible solutions:

The first possible solution I propose is to add the reporters name with Unicode character as a variation, but to make this work we need a small change, when we load reporters.json file in reporters_db [we need to set the encoding to utf-8](https://github.com/freelawproject/reporters-db/blob/main/reporters_db/__init__.py#L22), if we don’t do this we won’t be able to serialize Unicode characters, for example if we have “Bayard’s Notebook” as a variation, it will be loaded as “Bayardâ€™s Notebook” so we won’t be able to identify the reporter if we try to get citations from “Bayard’s Notebook, 38”.
For this solution, we will need to add the reporter with the Unicode character on each variation. It’s not that hard, but will take some time.

The second possible solution is easier, like @mlissner proposed, is to put the normalization inside get_citations() function, we only need to add the replace function at the beginning and that’s all.

As a third solution @mlissner suggested that maybe we could add another regex to reporters_db to match the left single quotation mark in the reporter’s name, but after inspecting how the regexes are generated and checked in “eyecite” I realized that the reporter edition name is hardcoded to make it match exactly with the citation, so I believe It's not as simple as adding an extra regex to reporters_db regexes.json. Anyone has a different idea about how to solve the problem with regex approach?

Do you think this possible solutions could work? Or do you think of something different to solve it?

**Comment by mlissner** [comment]
Thanks for digging in. 

The best solution is probably to do it in reporters-db. That's where we put variations, I think. 

Needing to set encoding to utf-8 in the `open` statement makes sense. We should make sure that semgrep is enabled so that doesn't digress later for Windows people (on Linux it probably works fine).

> we could add another regex to reporters_db

I forget how these work, but we use regexes for lots of the reporters. Shouldn't we be able to just add a regex for the affected reporters?

**Comment by quevon24** [comment]
> Thanks for digging in.
> 
> The best solution is probably to do it in reporters-db. That's where we put variations, I think.
> 
> Needing to set encoding to utf-8 in the `open` statement makes sense. We should make sure that semgrep is enabled so that doesn't digress later for Windows people (on Linux it probably works fine).
> 
> > we could add another regex to reporters_db
> 
> I forget how these work, but we use regexes for lots of the reporters. Shouldn't we be able to just add a regex for the affected reporters?

I thought the same thing, the problem is that we also need to add an additional regex to each reporter, for example if we want to accept Bayard's Notebook with left single quotation mark, which accepts citations like: Bayard's Notebook, 235 or 1 Bayard's Notebook, 235 we need to add two regexes to match with quotation mark or left single quotation mark:

```
"(?P<reporter>Bayard(.)s Notebook), $page",
"$volume_nominative ? (?P<reporter>Bayard(.)s Notebook), $page"
```

Reporter will look like this:
![image](https://user-images.githubusercontent.com/6474994/186973443-894bda53-514e-4621-bf9c-1be1b8777c10.png)

I think it's easier to add reporters name variations with unicode character:

![image](https://user-images.githubusercontent.com/6474994/186973518-2c4e8c04-e59c-483c-b0dd-b09901e696e9.png)

What do you think is the most appropriate solution?

**Comment by mlissner** [comment]
Either seems fine to me. I guess in some cases there might be a bunch of variations in which case doing the regexes will be easier, but I find the variations easier to reason about, so that's my usual approach, personally.
