### ISSUE TITLE
v2.5.0 is not published

### ISSUE THREAD

**Issue by mattdahl** [freelawproject/eyecite#145]
v2.5.0 was tagged (https://github.com/freelawproject/eyecite/releases/tag/v2.5.0) but it has not been published to pypi (https://pypi.org/project/eyecite/) and the documentation has also not been updated. I believe that this is supposed to happen automatically on a new tag, did something go wrong? @mlissner

**Comment by mlissner** [comment]
Yeah, it looks like the Github Action failed: 

 - PyPi: https://github.com/freelawproject/eyecite/actions/runs/3972560007/jobs/6810593541
 - Pdoc: https://github.com/freelawproject/eyecite/actions/runs/3972560008

Both failed to install poetry. We probably just need a new version. Want to take a stab at fixing it? I think we went through something similar in CourtListener. @albertisfu fixed it, IIRC?

**Comment by albertisfu** [comment]
Yeah, well, the failed actions seem to be from Jan 20 (before we updated the poetry installer in actions), so I think if you run the actions again, they should succeed.

**Comment by mlissner** [comment]
Yep, that worked. I tagged and released 2.5.1: https://pypi.org/project/eyecite/.

Thanks Matt.

**Comment by mattdahl** [comment]
Thank you!
