### ISSUE TITLE
Microscope needs automated deploys to pypi

### ISSUE THREAD

**Issue by mlissner** [freelawproject/eyecite#3]
Bill, do you think you could set these up and do a first deploy?

Does it make sense to include something like this in our new project template? I can't decide if it'd be helpful or annoying.

**Comment by mlissner** [comment]
@mattdahl, @jcushman, @flooie, I'm happy to share that:

1. We have renamed microscope to be called "Eyecite." As you might expect, microscope was taken. Eyecite is pretty good though! Github seems like it'll support your old git configs without any needed changes, but you might want to update them with something like:

        $ git remote set-url origin https://github.com/freelawproject/eyecite

1.  1.0 lives! https://pypi.org/project/eyecite/. 

Anything else we want to do before we announce this? I think it'll be a pretty popular project.

**Comment by mattdahl** [comment]
Great! I actually like "eyecite" better as a name.

The only problem I see right now is that the README formatting is messed up (I see that you switched from Markdown to rst).

I can integrate this into CL, unless someone is already working on that?

**Comment by mlissner** [comment]
I like eyecite too too. Works nicely alongside CourtListener that hears things, apparently.

Integration would be a great next step. If you're feeling really generous with your time, we also have https://github.com/freelawproject/courtlistener/issues/1230, which is to integrate the courts_db into CL. I'm honestly not sure if that's a major project or not.

**Comment by jcushman** [comment]
I like eyecite better as well -- more specific. While you're renaming
stuff, is it worth renaming the default branch from master to main? It's
now the default branch name on github for new repos, and we've been
gradually moving our projects over at LIL; easier to do now than later.

**Comment by flooie** [comment]
@jcushman that’s going to take some getting used to.  Still no love for the superior name cite-sight

**Comment by mlissner** [comment]
I'm for changing to `main`, but I haven't found time to figure out what it means technically (and FLP is not very good at git in general). Jack, if you or somebody else wants to lead us in doing this, I'm sure we'd follow, but after spending a lot of today switching to eyecite, my energy for this on our own is going to be low for a while.
