### ISSUE TITLE
Expose test factories

### ISSUE THREAD

**Issue by mattdahl** [freelawproject/eyecite#32]
I would like to use the handy object-creation factories that @jcushman created (https://github.com/freelawproject/eyecite/blob/master/tests/factories.py) to streamline CL's tests as well.

However, we (rightly imo) exclude the tests directory when we package eyecite for distribution (https://github.com/freelawproject/eyecite/blob/master/setup.py#L36).

I propose either:

1. Moving the `factories.py` file into the main `eyecite` directory; or
2. Putting the factory functions onto the Citation models directly as class methods (sort of a pseudo-constructor specifically for creating mock objects)

Thoughts?

**Comment by mlissner** [comment]
Just exposing them seems like the easiest thing to me. From a documentation perspective, it seems pretty easy to explain that, "If you want to do tests in your own system, you can do so by importing xyz."

**Comment by mlissner** [comment]
Maybe a pseudocode of the second approach would help me see the vision.

**Comment by mlissner** [comment]
Fixed via #47
