### ISSUE TITLE
Logo design feedback

### ISSUE THREAD

**Issue by mlissner** [freelawproject/eyecite#44]
We're doing a homepage revamp and had some logos made for the projects that we want to advertise on free.law.

The logos we've done so far were very cheap, and I don't think they're ready or very good yet, but here's the one for eyecite. 

![eye](https://user-images.githubusercontent.com/236970/112220159-2b95b280-8be3-11eb-8af6-5387a9465ee6.png)

Comments and feedback very welcome!

**Comment by mattdahl** [comment]
I like the general eye motif, and the veins/branches too. However, I feel like it should be more horizontal, not so vertical. Also, maybe add a brighter color, like an orange, somewhere?

Just my thoughts, I am not a designer.
