### ISSUE TITLE
More obscure joke?

### ISSUE THREAD

**Issue by jcushman** [freelawproject/eyecite#60]
CAP's extraction task choked on a few cases because of the `joke_cite`, since we extract citations paragraph by paragraph and have some paragraphs that are just the word "this", and the code wasn't expected a cite with `reporter_found=None`. Maybe time for a new joke?

<img width="488" alt="image" src="https://user-images.githubusercontent.com/376272/115260106-72060080-a100-11eb-8aa3-41337413126d.png">

**Comment by mlissner** [comment]
Oh no. That was the one thing I thought I could pull off, but a voice in my head said, "Mike, this joke will introduce bugs."

**Comment by mlissner** [comment]
"This will add to the maintenance burden, Mike."

**Comment by mlissner** [comment]
"But jokes are worth it, Mike. People will enjoy this, Mike."

**Comment by jcushman** [comment]
Cool thanks for fixing that forever.
