### ISSUE TITLE
Trailing comma in defendant field of full case citation

### ISSUE THREAD

**Issue by ProbablyFaiz** [freelawproject/eyecite#66]
While writing some tests to expose the issues pointed out by @jcushman in #62, I noticed that eyecite was capturing the comma separating the defendant of a case and the reporter citation and making it part of the defendant string. Checked some real text we're working with, same issue.

Here's a minimum reproducible example:
```python
import eyecite

input_str = 'foo v. bar, 1 U.S. 1 (2021)'
citations = eyecite.get_citations(input_str)
print(citations[0].defendant) # Prints 'bar,'
```

If this behavior isn't intended and we can safely assume that party names don't end in commas, it can be relatively trivially fixed by simply stripping commas (as well as whitespace) off the defendant name:

https://github.com/freelawproject/eyecite/blob/586cbb481e17a5e02f84a280601bd0e60acfa6c4/eyecite/helpers.py#L121-L123
```python
from string import whitespace
# ...
citation.metadata.defendant = "".join(
    str(w) for w in words[start_index : citation.index]
).strip(whitespace + ',')
```

Happy to create a new PR with this fix and a test to cover it, or fold it into #62. Just wanted to check if this is on purpose first.

**Comment by jcushman** [comment]
Stripping commas sounds right to me. Go for it!

`eyecite` assumes that all whitespace is `' '` or `'\n'`, so you can just `strip(" ,")`.

(Specifically `eyecite` assumes that input text has been passed through the equivalent of `cleaners.inline_whitespace` or `cleaners.all_whitespace`, depending whether line breaks represent paragraph breaks or word breaks in your input. Comparing those cleaners to `string.whitespace`, it's possible that `inline_whitespace` should be handling `'\v\f'` the same as `'\t'`, and replacing `[\n\r]+` with `\n`.)

(FWIW I think in the long run we want to extract case names and antecedents with a regex that looks for capitalized words plus specific non-capitalized things, but that's a bigger project.)

**Comment by ProbablyFaiz** [comment]
Will do, thanks!

> (FWIW I think in the long run we want to extract case names and antecedents with a regex that looks for capitalized words plus specific non-capitalized things, but that's a bigger project.)

Noticed this as well (e.g. Heart of Atlanta Motel Inc. v. United States registers plaintiff "Inc."). It strikes me as really tricky to get right without prior knowledge of real case names though. A real example from an opinion I was looking at today: "In *Lopez* and *Perez v. United States*, 402 U.S. 146 (1971), the Court..." Without formatting or context, I have no intuition on how to determine whether the plaintiff's name should be "Perez", "Lopez and Perez", or "In Lopez and Perez".
