### ISSUE TITLE
License of deps

### ISSUE THREAD

**Issue by pombredanne** [freelawproject/eyecite#83]
This project is BSD-licensed, but it depends on @asciimoo https://github.com/asciimoo/exrex which is using the AGPL.... my understanding is that the AGPL may extend here too.  @asciimoo have you consider the usage of your tool as a library and its license impact?

**Comment by mlissner** [comment]
Hi, we just use exrex for tests, and so it's a murky area as to whether there is a conflict. Those using Eyecite, for example, aren't receiving or using exrex code.

That said, if the copyright owner of exrex wants to discuss our use of exrex in our code, we'd be happy to do so or to remove it from our tests. Such issues can be discussed via legal@free.law. 

Closing for now, but happy to discuss via email with exrex maintainers if they are interested.

**Comment by pombredanne** [comment]
Sorry for the noise: I do not think there is any issue! this is a dev dep alright!

**Comment by asciimoo** [comment]
@mlissner I agree, it is only a dev dependency. AFAIK this kind of usage doesn't conflict with the AGPL, feel free to use it. =]

**Comment by mlissner** [comment]
Thank you for the wonderful tool!
