### ISSUE TITLE
Project does not have community guidelines

### ISSUE THREAD

**Issue by cmaimone** [freelawproject/eyecite#90]
RE: https://github.com/openjournals/joss-reviews/issues/3617 

I don't see any of the expected community guidelines:  
Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by mlissner** [comment]
Thanks @cmaimone. I added a new section to the readme with some details. Please let me know if you have further concerns and I'll be happy to try to help.

**Comment by cmaimone** [comment]
I saw the license agreement, but the guidelines were asking for more than that (unless I missed some other part).  See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors for some suggestions at setting up good contributor guidelines

**Comment by step21** [comment]
I would also say - as there is a CLA in repo - if you expect people to sign a CLA for contributions, this should definitely be mentioned in the contribution guidelines.

**Comment by mlissner** [comment]
It is in the readme, but yeah, it'd be good to move it over to the contributor guidelines file. I'll take a stab at that.
