### ISSUE TITLE
API/Reference Documentation

### ISSUE THREAD

**Issue by cmaimone** [freelawproject/eyecite#92]
RE: https://github.com/openjournals/joss-reviews/issues/3617

I see the tutorial in the repo readme, but is there reference/API documentation somewhere -- that lists the functions, classes, etc. in the package, with parameters, etc.  (the type generally generated from docstrings)

I expect this type of documentation for packages (or alternatively much more extensive usage guides)

**Comment by mlissner** [comment]
We don't have that at present. I've never generated that. @jcushman do you have any experience with generating this kind of thing?

**Comment by step21** [comment]
This could maybe also be partially automated. There is at least some use of docstrings in the code, these could f.e. be parsed by pdoc, sphinx or a similar documentation tool.

**Comment by mlissner** [comment]
OK, this is now live at: https://freelawproject.github.io/eyecite/, and will auto-generate via a Github Action whenever a new version is tagged and pushed.

Thank you for this request!

**Comment by step21** [comment]
Cool. Looks great.
