### ISSUE TITLE
More concise list of functionality

### ISSUE THREAD

**Issue by cmaimone** [freelawproject/eyecite#94]
RE: https://github.com/openjournals/joss-reviews/issues/3617

It would help in the tutorial/documentation/readme to have a more concise list of what the functionality of the package is -- what are the main things it does.  This could be as simple as a table of contents for the tutorial sections, if all of the functionality is represented by a section.

**Comment by mlissner** [comment]
I think this should be all set. Do you want to take a look and close this issue if resolved?
