### ISSUE TITLE
References to "database" in tutorial

### ISSUE THREAD

**Issue by cmaimone** [freelawproject/eyecite#95]
RE: https://github.com/openjournals/joss-reviews/issues/3617

There are references to a "database" in the tutorial - I don't know what these mean.  What database?  Are you talking about linking to external legal databases of some type?  Are these just adding URLs?

It also says things like "fetched from our database" -- but what is "our database"?

**Comment by cmaimone** [comment]
Related to the above, the entire section

> Now we want to resolve all of the extracted cites into clusters indexed by the resource they refer to, such as a case or statute. We'll use a custom function to resolve a given full cite to its resource, so we can return our own MyCaseModel for citations we recognize. We'll fall back on returning resolve_full_citation() for citations we don't recognize.
> 
> For this simplified example, we'll assume we have a database model MyCaseModel so that MyCaseModel.get_by_citation() will return the case referred to by that citation string. In real life this might be a Django model or Elasticsearch lookup. We'll also assume that the same case has the parallel citations "1 U.S. 2" and "1 S. Ct. 2", so MyCaseModel.get_by_citation("1 U.S. 2") returns the same case as MyCaseModel.get_by_citation("1 S. Ct. 2").

I got lost.  I think you're saying you have a hypothetical database with a table model class in it, separate from this package.  This is super confusing for folks who aren't familiar with this type of setup or don't have their own database.  Do you have to use a database for the citation resolution?  All code in the tutorial (with maybe a few exceptions for special use cases, etc.) should be able to run by a potential user.  I can't test the resolve_citations() functionality because the example code uses a database I don't have (and there aren't instructions to set one up.

**Comment by mlissner** [comment]
Hopefully this should be clear now too. Could you take a look and hopefully it'll be better? Thank you for the helpful feedback.

**Comment by cmaimone** [comment]
It's clearer, but I still think the code in the tutorial should be mostly run-able if possible.  For the custom_resolution_callback function, could you make a very simple one that just looked up values in a dict or something similar?  And also code to make your SomeCustomObject class?  This "class" gets used later for annotation examples too.  

Or can you call one of the APIs if they're open (no key) to show a real example?

I'm not going to hold up the paper publication over this, but sorting out some of these things should help eyecite be more clearly and functionally a stand-alone package, that doesn't rely on such close integration with the systems it was developed for.

**Comment by mattdahl** [comment]
Hi @cmaimone, we've now extracted the tutorial into its own Jupyter notebook: https://github.com/freelawproject/eyecite/blob/main/TUTORIAL.ipynb. We think that this (1) provides a more realistic demonstration for the reader (e.g., by pulling a sample opinion from an API, as you suggested) and (2) makes clear that all the code is run-able by the reader (and modifiable by them, if they want to play around more with the example in Jupyter). What do you think?

**Comment by cmaimone** [comment]
Awesome!  That seems really helpful.

**Comment by mlissner** [comment]
I'm going to go ahead and close this one. Seems like it's all set, but please let me know if I'm too eager.
