### ISSUE TITLE
Paper structure

### ISSUE THREAD

**Issue by step21** [freelawproject/eyecite#98]
Re: https://github.com/openjournals/joss-reviews/issues/3617

Once or twice I had the feeling that the paper switches between topics or mixes things. As example, under 'statement of need' it switches from explaining the need directly to explaining how eyecite itself works.
Maybe this could be its own section?

**Comment by mlissner** [comment]
@step21, I just merged #99, which attempts to address this. Are you a good person to decide if this issue is thus resolved?

**Comment by step21** [comment]
Seems great. Thanks! I'd say as I raised the issue, I am also a good person to decide it is solved.

**Comment by mlissner** [comment]
Thank you!
